---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mlipkb2eqfwq/public_html/formula-fantasy.com/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp ff_white.png $DEPLOYPATH
    - /bin/cp test.html $DEPLOYPATH
    - export DEPLOYPATHCSS=/home/mlipkb2eqfwq/public_html/formula-fantasy.com/css/
    - /bin/cp css/reset.css $DEPLOYPATHCSS
    - /bin/cp css/style.css $DEPLOYPATHCSS
    - export DEPLOYPATHIMG=/home/mlipkb2eqfwq/public_html/formula-fantasy.com/img/
    - /bin/cp img/img.png $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-1.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-2.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-3.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-4.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-5.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-6.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-7.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-8.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-9.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-10.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-11.svg $DEPLOYPATHIMG
    - /bin/cp img/nucleo-icon-12.svg $DEPLOYPATHIMG
    - export DEPLOYPATHJS=/home/mlipkb2eqfwq/public_html/formula-fantasy.com/js/
    - /bin/cp js/jquery-2.1.1.js $DEPLOYPATHJS
    - /bin/cp js/jquery.menu-aim.js $DEPLOYPATHJS
    - /bin/cp js/main.js $DEPLOYPATHJS
    - /bin/cp js/modernizr.js $DEPLOYPATHJS